### PR TITLE
Migrating to solana v1.17.15

### PR DESCRIPTION
**Pull request by godmodegalactus**

### CODE REVIEW

**Comment by grooviegermanikus** [comment]
should bump LiteRPC version maybe

**Comment by godmodegalactus** [comment]
> should bump LiteRPC version maybe

I will update once I fixed the main issue

**Comment by grooviegermanikus** [comment]
checked this - looked good:

> cargo tree -i tonic
cargo tree -i rustls
cargo tree -i quinn

**Review by grooviegermanikus — APPROVED** [review]
LGTM

**Pull request merged**
